version: "3.3"

services:

  bot:
    build: bot/

    command: python /run.py

  database:
    build: database/

    command: python /database.py

networks:
  default:
    name: bridge-nerwork
    external: true
